name: mobile_app_new
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Required for making HTTP requests
  http: ^1.2.1

  uuid: ^3.0.6

  # For fingerprint authentication
  local_auth: ^2.1.3


  flutter_secure_storage: ^8.0.0

  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  firebase_messaging: ^14.7.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
